# Generated by Django 5.0.6 on 2024-06-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='video_url',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
