# Generated by Django 5.0.6 on 2024-06-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_coursecontent_video_url_coursecontent_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_backgrounds/'),
        ),
        migrations.AddField(
            model_name='course',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_backgrounds/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_backgrounds/'),
        ),
    ]
