# Generated by Django 5.0.6 on 2024-06-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicum', '0002_alter_major_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_backgrounds/'),
        ),
        migrations.AddField(
            model_name='major',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='major_backgrounds/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_backgrounds/'),
        ),
    ]
